from pyspark import SparkConf, SparkContext
import collections

conf = SparkConf().setMaster('local').setAppName('airPortTraffic')
sc = SparkContext(conf = conf)


def parseLine(lines):
    fields = lines.split(',')
    airline = fields[1]
    acType = fields[7]
    passengerCount = int(fields[11])
    return ((airline, acType), passengerCount)


rdd = sc.textFile('Air_Traffic_Passenger_Statistics.csv').map(parseLine)
rdd1 = rdd.reduceByKey(lambda x , y: x+y)


# print(rdd.keys())

# results = rdd1.collect()

# for result in results:
#     print(result)
#

from pyspark.sql import SparkSession
from pyspark.sql import Row

spark = SparkSession.builder.config('spark.sql.warehouse.dir','file:///c:/temp').appName('thisSQLversion').getOrCreate()

rdd = spark.sparkContext.textFile('file:///sparkCourse/Air_Traffic_Passenger_Statistics.csv')

def parsedf (lines):
    fields = lines.split(',')
    airline = fields[1]
    acType = fields[7]
    passengerCount = int(fields[11])
    return Row(airline = airline, activityType = acType, count = passengerCount)

pre_df = rdd.map(parsedf)

df = spark.createDataFrame(pre_df).cache()
df.createOrReplaceTempView('df')

query = spark.sql("select airline, activityType, sum(count) as total from df group by airline, activityType order by sum(count)")

for result in query.collect():
    print(result)


spark.stop()


# Row(airline='Evergreen International Airlines', activityType='Enplaned', total=2)
# Row(airline='Evergreen International Airlines', activityType='Deplaned', total=2)
# Row(airline='Atlas Air. Inc', activityType='Thru / Transit', total=3)
# Row(airline='Ameriflight', activityType='Thru / Transit', total=8)
# Row(airline='Boeing Company', activityType='Deplaned', total=18)
# Row(airline='Ameriflight', activityType='Deplaned', total=30)
# Row(airline='Atlas Air. Inc', activityType='Deplaned', total=65)
# Row(airline='Ameriflight', activityType='Enplaned', total=72)
# Row(airline='Xtra Airways', activityType='Deplaned', total=73)
# Row(airline='Xtra Airways', activityType='Enplaned', total=73)
# Row(airline='Swissport USA', activityType='Thru / Transit', total=93)
# Row(airline='Trego Dugan Aviation', activityType='Deplaned', total=108)
# Row(airline='WestJet Airlines', activityType='Thru / Transit', total=137)
# Row(airline='Compass Airlines', activityType='Thru / Transit', total=149)
# Row(airline='Pacific Aviation', activityType='Enplaned', total=160)
# Row(airline='Pacific Aviation', activityType='Deplaned', total=160)
# Row(airline='SkyWest Airlines', activityType='Thru / Transit', total=223)
# Row(airline='World Airways', activityType='Deplaned', total=255)
# Row(airline='BelAir Airlines', activityType='Thru / Transit', total=278)
# Row(airline='Japan Airlines', activityType='Thru / Transit', total=284)
# Row(airline='Trego Dugan Aviation', activityType='Enplaned', total=304)
# Row(airline='XL Airways France', activityType='Thru / Transit', total=526)
# Row(airline='World Airways', activityType='Enplaned', total=530)
# Row(airline='Hong Kong Airlines Limited', activityType='Thru / Transit', total=611)
# Row(airline='Miami Air International', activityType='Enplaned', total=733)
# Row(airline='Miami Air International', activityType='Deplaned', total=985)
# Row(airline='Servisair', activityType='Deplaned', total=1494)
# Row(airline='Servisair', activityType='Enplaned', total=1748)
# Row(airline='Air Canada Jazz', activityType='Enplaned', total=1985)
# Row(airline='Air Canada Jazz', activityType='Deplaned', total=2134)
# Row(airline='Swissport USA', activityType='Enplaned', total=2391)
# Row(airline='Swissport USA', activityType='Deplaned', total=2619)
# Row(airline='Icelandair EHF', activityType='Deplaned', total=2727)
# Row(airline='Icelandair EHF', activityType='Enplaned', total=3581)
# Row(airline='BelAir Airlines', activityType='Deplaned', total=4039)
# Row(airline='French Bee', activityType='Deplaned', total=4799)
# Row(airline='BelAir Airlines', activityType='Enplaned', total=4821)
# Row(airline='French Bee', activityType='Enplaned', total=5325)
# Row(airline='French Bee', activityType='Thru / Transit', total=5628)
# Row(airline='Iberia', activityType='Enplaned', total=6791)
# Row(airline='Iberia', activityType='Deplaned', total=6871)
# Row(airline='Delta Air Lines', activityType='Thru / Transit', total=7426)
# Row(airline='ABC Aerolineas S.A. de C.V. dba Interjet', activityType='Deplaned', total=7530)
# Row(airline='ABC Aerolineas S.A. de C.V. dba Interjet', activityType='Enplaned', total=8055)
# Row(airline='Allegiant Air', activityType='Enplaned', total=12090)
# Row(airline='Allegiant Air', activityType='Deplaned', total=12179)
# Row(airline='Southwest Airlines', activityType='Thru / Transit', total=12820)
# Row(airline='Hong Kong Airlines Limited', activityType='Deplaned', total=14331)
# Row(airline='Hong Kong Airlines Limited', activityType='Enplaned', total=15793)
# Row(airline='Finnair', activityType='Enplaned', total=17215)
# Row(airline='Thomas Cook Airlines', activityType='Deplaned', total=18525)
# Row(airline='Finnair', activityType='Deplaned', total=18651)
# Row(airline='Thomas Cook Airlines', activityType='Enplaned', total=18958)
# Row(airline='Atlantic Southeast Airlines', activityType='Deplaned', total=22251)
# Row(airline='Northwest Airlines', activityType='Thru / Transit', total=23101)
# Row(airline='Atlantic Southeast Airlines', activityType='Enplaned', total=25641)
# Row(airline='Icelandair', activityType='Enplaned', total=26860)
# Row(airline='Icelandair', activityType='Deplaned', total=29134)
# Row(airline='Republic Airlines', activityType='Deplaned', total=29134)
# Row(airline='Republic Airlines', activityType='Enplaned', total=29726)
# Row(airline='Independence Air', activityType='Deplaned', total=31357)
# Row(airline='Jet Airways', activityType='Enplaned', total=32077)
# Row(airline='Independence Air', activityType='Enplaned', total=32556)
# Row(airline='Spirit Airlines', activityType='Deplaned', total=32933)
# Row(airline='Air Pacific Limited dba Fiji Airways', activityType='Enplaned', total=33561)
# Row(airline='Air Pacific Limited dba Fiji Airways', activityType='Deplaned', total=34254)
# Row(airline='Jet Airways', activityType='Deplaned', total=36408)
# Row(airline='Spirit Airlines', activityType='Enplaned', total=37172)
# Row(airline='ATA Airlines', activityType='Thru / Transit', total=40349)
# Row(airline='XL Airways France', activityType='Enplaned', total=57570)
# Row(airline='XL Airways France', activityType='Deplaned', total=60865)
# Row(airline='Mesaba Airlines', activityType='Deplaned', total=62620)
# Row(airline='Mesaba Airlines', activityType='Enplaned', total=63428)
# Row(airline='Jazz Aviation', activityType='Deplaned', total=78074)
# Row(airline='Jazz Aviation', activityType='Enplaned', total=78713)
# Row(airline='ExpressJet Airlines', activityType='Deplaned', total=86763)
# Row(airline='ExpressJet Airlines', activityType='Enplaned', total=93456)
# Row(airline='Volaris Airlines', activityType='Enplaned', total=98779)
# Row(airline='United Airlines', activityType='Thru / Transit', total=101316)
# Row(airline='Volaris Airlines', activityType='Deplaned', total=103956)
# Row(airline='Air Berlin', activityType='Enplaned', total=113644)
# Row(airline='Air Berlin', activityType='Deplaned', total=121511)
# Row(airline='LAN Peru', activityType='Enplaned', total=125095)
# Row(airline='LAN Peru', activityType='Deplaned', total=125646)
# Row(airline='Air India Limited', activityType='Enplaned', total=139974)
# Row(airline='WOW Air', activityType='Deplaned', total=146052)
# Row(airline='WOW Air', activityType='Enplaned', total=149116)
# Row(airline='Air India Limited', activityType='Deplaned', total=153525)
# Row(airline='ATA Airlines', activityType='Deplaned', total=168621)
# Row(airline='ATA Airlines', activityType='Enplaned', total=175794)
# Row(airline='Etihad Airways', activityType='Enplaned', total=182806)
# Row(airline='COPA Airlines. Inc.', activityType='Deplaned', total=205249)
# Row(airline='American Eagle Airlines', activityType='Enplaned', total=205465)
# Row(airline='COPA Airlines. Inc.', activityType='Enplaned', total=206989)
# Row(airline='Etihad Airways', activityType='Deplaned', total=212788)
# Row(airline='Midwest Airlines', activityType='Deplaned', total=213276)
# Row(airline='Mesa Airlines', activityType='Enplaned', total=214118)
# Row(airline='American Eagle Airlines', activityType='Deplaned', total=219227)
# Row(airline='Mesa Airlines', activityType='Deplaned', total=220066)
# Row(airline='Alaska Airlines', activityType='Thru / Transit', total=235093)
# Row(airline='Midwest Airlines', activityType='Enplaned', total=237152)
# Row(airline='China Southern', activityType='Enplaned', total=264527)
# Row(airline='China Southern', activityType='Deplaned', total=277771)
# Row(airline='Turkish Airlines', activityType='Enplaned', total=329878)
# Row(airline='Turkish Airlines', activityType='Deplaned', total=338407)
# Row(airline='SAS Airlines', activityType='Enplaned', total=378303)
# Row(airline='SAS Airlines', activityType='Deplaned', total=385229)
# Row(airline='Aer Lingus', activityType='Enplaned', total=387647)
# Row(airline='Aer Lingus', activityType='Deplaned', total=390044)
# Row(airline='WestJet Airlines', activityType='Deplaned', total=397275)
# Row(airline='WestJet Airlines', activityType='Enplaned', total=402389)
# Row(airline='China Eastern', activityType='Enplaned', total=417908)
# Row(airline='China Eastern', activityType='Deplaned', total=448631)
# Row(airline='Mexicana Airlines', activityType='Deplaned', total=482117)
# Row(airline='Mexicana Airlines', activityType='Enplaned', total=509115)
# Row(airline='Qantas Airways', activityType='Enplaned', total=519851)
# Row(airline='Qantas Airways', activityType='Deplaned', total=559298)
# Row(airline='Swiss International', activityType='Enplaned', total=627939)
# Row(airline='Swiss International', activityType='Deplaned', total=648732)
# Row(airline='Horizon Air', activityType='Deplaned', total=654014)
# Row(airline='Horizon Air', activityType='Enplaned', total=677570)
# Row(airline='Sun Country Airlines', activityType='Enplaned', total=693161)
# Row(airline='Sun Country Airlines', activityType='Deplaned', total=696769)
# Row(airline='TACA', activityType='Enplaned', total=807294)
# Row(airline='TACA', activityType='Deplaned', total=811379)
# Row(airline='Aeromexico', activityType='Deplaned', total=828202)
# Row(airline='Aeromexico', activityType='Enplaned', total=844744)
# Row(airline='Asiana Airlines', activityType='Enplaned', total=953330)
# Row(airline='United Airlines - Pre 07/01/2013', activityType='Thru / Transit', total=969406)
# Row(airline='All Nippon Airways', activityType='Enplaned', total=994878)
# Row(airline='Japan Airlines', activityType='Enplaned', total=999634)
# Row(airline='Asiana Airlines', activityType='Deplaned', total=1001258)
# Row(airline='Japan Airlines', activityType='Deplaned', total=1008170)
# Row(airline='All Nippon Airways', activityType='Deplaned', total=1021915)
# Row(airline='Korean Air Lines', activityType='Enplaned', total=1032122)
# Row(airline='Korean Air Lines', activityType='Deplaned', total=1059459)
# Row(airline='Air China', activityType='Enplaned', total=1113421)
# Row(airline='Emirates', activityType='Enplaned', total=1131274)
# Row(airline='Air China', activityType='Deplaned', total=1146913)
# Row(airline='Emirates', activityType='Deplaned', total=1169648)
# Row(airline='Air New Zealand', activityType='Enplaned', total=1176300)
# Row(airline='AirTran Airways', activityType='Deplaned', total=1186534)
# Row(airline='AirTran Airways', activityType='Enplaned', total=1202114)
# Row(airline='Air New Zealand', activityType='Deplaned', total=1204007)
# Row(airline='KLM Royal Dutch Airlines', activityType='Enplaned', total=1478281)
# Row(airline='Hawaiian Airlines', activityType='Deplaned', total=1493455)
# Row(airline='Hawaiian Airlines', activityType='Enplaned', total=1498951)
# Row(airline='China Airlines', activityType='Deplaned', total=1542688)
# Row(airline='KLM Royal Dutch Airlines', activityType='Deplaned', total=1543408)
# Row(airline='China Airlines', activityType='Enplaned', total=1557613)
# Row(airline='Philippine Airlines', activityType='Enplaned', total=1577633)
# Row(airline='Virgin Atlantic', activityType='Enplaned', total=1596915)
# Row(airline='Virgin Atlantic', activityType='Deplaned', total=1597118)
# Row(airline='Philippine Airlines', activityType='Deplaned', total=1690280)
# Row(airline='Compass Airlines', activityType='Deplaned', total=1735844)
# Row(airline='Compass Airlines', activityType='Enplaned', total=1742151)
# Row(airline='Air France', activityType='Deplaned', total=1894549)
# Row(airline='Air France', activityType='Enplaned', total=1906489)
# Row(airline='EVA Airways', activityType='Enplaned', total=2173201)
# Row(airline='EVA Airways', activityType='Deplaned', total=2214169)
# Row(airline='Singapore Airlines', activityType='Deplaned', total=2251977)
# Row(airline='Singapore Airlines', activityType='Enplaned', total=2278730)
# Row(airline='Cathay Pacific', activityType='Enplaned', total=2747840)
# Row(airline='British Airways', activityType='Deplaned', total=2774657)
# Row(airline='British Airways', activityType='Enplaned', total=2779075)
# Row(airline='Cathay Pacific', activityType='Deplaned', total=2798970)
# Row(airline='Frontier Airlines', activityType='Enplaned', total=2943104)
# Row(airline='Frontier Airlines', activityType='Deplaned', total=2991767)
# Row(airline='Lufthansa German Airlines', activityType='Enplaned', total=3037340)
# Row(airline='Lufthansa German Airlines', activityType='Deplaned', total=3088757)
# Row(airline='Northwest Airlines', activityType='Deplaned', total=3119475)
# Row(airline='Northwest Airlines', activityType='Enplaned', total=3123644)
# Row(airline='Air Canada', activityType='Deplaned', total=4380183)
# Row(airline='Air Canada', activityType='Enplaned', total=4424711)
# Row(airline='JetBlue Airways', activityType='Deplaned', total=5685621)
# Row(airline='JetBlue Airways', activityType='Enplaned', total=5713118)
# Row(airline='US Airways', activityType='Deplaned', total=8362406)
# Row(airline='US Airways', activityType='Enplaned', total=8454210)
# Row(airline='Alaska Airlines', activityType='Deplaned', total=8511971)
# Row(airline='Alaska Airlines', activityType='Enplaned', total=8793171)
# Row(airline='Southwest Airlines', activityType='Enplaned', total=16619309)
# Row(airline='Southwest Airlines', activityType='Deplaned', total=16782841)
# Row(airline='Delta Air Lines', activityType='Enplaned', total=17396070)
# Row(airline='Delta Air Lines', activityType='Deplaned', total=17410337)
# Row(airline='Virgin America', activityType='Deplaned', total=18835973)
# Row(airline='Virgin America', activityType='Enplaned', total=19007947)
# Row(airline='American Airlines', activityType='Enplaned', total=21756824)
# Row(airline='American Airlines', activityType='Deplaned', total=21865563)
# Row(airline='SkyWest Airlines', activityType='Enplaned', total=22235353)
# Row(airline='SkyWest Airlines', activityType='Deplaned', total=22346780)
# Row(airline='United Airlines - Pre 07/01/2013', activityType='Enplaned', total=52081618)
# Row(airline='United Airlines - Pre 07/01/2013', activityType='Deplaned', total=52312893)
# Row(airline='United Airlines', activityType='Enplaned', total=56151982)
# Row(airline='United Airlines', activityType='Deplaned', total=56387110)
